services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpassword
      MYSQL_DATABASE: flaskapp
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql