"""example table

Revision ID: bdfedb99b1d5
Revises: 
Create Date: 2025-04-25 02:16:18.042364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdfedb99b1d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bigger_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_entry', sa.Boolean(), nullable=True),
    sa.Column('freeflow', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('example_table')
    # ### end Alembic commands ###
